name: Pokedex continous integration
on: push
jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: update index
        run: helm repo index .
      
      - name: commit-push update index
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Update charts index
